services:
  fluxzero-runtime:
    image: ghcr.io/fluxzero-io/fluxzero-sdk-java/fluxzero-test:1.20.0
    environment:
      - FLUXZERO_LOG_RETENTION=PT30M
    healthcheck:
      test: "wget --spider -q http://localhost:8888/health"
      interval: 5s
    ports:
      - "8888:8888"

  meepleverse:
    image: ghcr.io/fluxzero-io/fluxzero-sdk-java/fluxzero-proxy:1.20.0
    environment:
      - FLUXZERO_BASE_URL=http://fluxzero-runtime:8888
      - FLUXZERO_APPLICATION_NAME=meepleverse-proxy
    ports:
      - "8080:8080"

  supplier-service:
    build:
      context: supplier
    environment:
      - FLUXZERO_BASE_URL=http://fluxzero-runtime:8888
      - FLUXZERO_APPLICATION_NAME=supplier-service
      - meepleverse.url=
    depends_on:
      fluxzero-runtime:
        condition: service_healthy

  psp-service:
    build:
      context: psp
    environment:
      - FLUXZERO_BASE_URL=http://fluxzero-runtime:8888
      - FLUXZERO_APPLICATION_NAME=psp-service
    depends_on:
      fluxzero-runtime:
        condition: service_healthy

  shipper-service:
    build:
      context: shipper
    environment:
      - FLUXZERO_BASE_URL=http://fluxzero-runtime:8888
      - FLUXZERO_APPLICATION_NAME=shipper-service
    depends_on:
      fluxzero-runtime:
        condition: service_healthy

  opensearch:
    image: opensearchproject/opensearch:3
    environment:
      - discovery.type=single-node
#      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=0pen_Search
      - DISABLE_SECURITY_PLUGIN=true
    healthcheck:
      test: "curl -fs http://localhost:9200/_cluster/health?wait_for_status=yellow"
      interval: 10s

  dashboards:
    build:
      context: dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
    ports:
      - "5601:5601"
    depends_on:
      opensearch:
        condition: service_healthy
    healthcheck:
      test: "curl -fs http://localhost:5601/api/status"

  auditlog:
    image: ghcr.io/fluxzero-io/fluxzero-auditlog-opensearch:v1.2.1
    environment:
      - FLUXZERO_BASE_URL=http://fluxzero-runtime:8888
      - OPENSEARCH_URL=http://opensearch:9200
      - AUDITLOG_USER=admin
      - AUDITLOG_PASSWORD=0pen_Search
      - DASHBOARDS_URL=http://dashboards:5601
      - DASHBOARDS_USER=admin
      - DASHBOARDS_PASSWORD=0pen_Search
    depends_on:
      dashboards:
        condition: service_healthy
      fluxzero-runtime:
        condition: service_healthy